### ISSUE TITLE
tries to minify index.js file in dist-types... But there isn't one.

### ISSUE THREAD

**Issue by MarkLyck** [michael-klein/pika-plugin-minify#3]
When I add `pika-plugin-minify` to my pika build pipeline I get the following error:

`Error: ENOENT: no such file or directory, open '/Users/marklyck/colony/colony-ui/pkg/dist-types/index.js'`

My library is build with Typescript and this is my pika setup:

```
"@pika/pack": {
        "pipeline": [
            ["@pika/plugin-ts-standard-pkg"],
            ["@pika/plugin-build-web"],
            ["pika-plugin-minify"]
        ]
    },
```

nothing special... But yet this minify plugin is trying to minify a non-existent index.js file in the types output?

This is completely preventing me from using pika for any production ready code.

Full output:

```
[5/6] Running pika-plugin-minify...
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/marklyck/colony/colony-ui/pkg/dist-types/index.js'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at /Users/marklyck/colony/colony-ui/node_modules/pika-plugin-minify/dist-node/index.js:71:27
    at FSReqCallback.oncomplete (fs.js:159:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/marklyck/colony/colony-ui/pkg/dist-types/index.js'
}
Error: Command failed with exit code 1 (EPERM): npx pika-pack
    at makeError (/usr/local/lib/node_modules/@pika/cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/@pika/cli/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runExternalCommand (/usr/local/lib/node_modules/@pika/cli/dist-node/index.js:83:5)
    at async cli (/usr/local/lib/node_modules/@pika/cli/dist-node/index.js:141:43)
(base)
```

**Comment by victordidenko** [comment]
Same here...
PR #2 should fix this, but this plugin is abandoned?
